# This is the ipcop (CGI) language file with english text which are not yet inserted into the language
# database.
# Developers can insert new language texts here to have them on the ISO for testing until someone adds
# them to the database. If you add a language text to the database, please delete it here to avoid confusion.



%tr_new = (

######## Start Edit below ##########

#'access from red any is not allowed' => 'An Accept rule with source interface RED or Any is not allowed',
#'address grouping settings txt' => 'Address Grouping',
#'address settings txt' => 'Address settings',
#'adv firewall config' => 'Advanced BOT Config',
#'allow related, established' => 'Allow related, established',
#'allow related, established connections' => 'Allow related, established connections',
#'block out traff' => 'BlockOutTraffic',
#'block out traff is' => 'BlockOutTraffic is ',
#'blockouttraffic configuration' => 'BlockOutTraffic Configuration',
#'common firewall rule' => 'Common Firewall Rule',
#'connection state' => 'Connection state',
#'dhcp server disabled on blue interface' => 'DHCP server disabled on BLUE interface',
#'dhcp server enabled on blue interface' => 'DHCP server enabled on BLUE interface',
#'disable bot' => 'Disable BOT',
#'disable bot before edit settings' => 'Disable BlockOutTraffic before edit settings.',
#'disabledtitle' => 'Disabled',
#'enable bot' => 'Enable BOT',
#'error destination address in more secure network' => 'You can\'t create a rule with destination address in a more secure network (e.g. from Blue -&gt; Green Network)',
#'fw blue' => 'Blue',
#'fw green' => 'Green',
#'fw green vpn' => 'Green / VPN',
#'fw orange' => 'Orange',
#'fw red' => 'Red',
#'https port bad' => 'Invalid HTTPS port',
#'https port default 445' => 'HTTPS Port (Default is 445)',
#'https port' => 'HTTPS Port',
#'iface color long' => 'Interface color',
#'interface colorlevel blue' => 'All blue, orange, red interfaces',
#'interface colorlevel green' => 'All green, VPN, blue, orange, red interfaces',
#'interface colorlevel orange' => 'All orange, red interfaces',
#'interface colorlevel red' => 'All red interfaces',
#'interfaces settings txt' => 'Interfaces settings',
#'invalid iface color' => 'Invalid interface color',
#'invalid src port' => 'Invalid Source port',
#'ipcop access only from green and blue' => 'IPCop access is only allowed from Green and Blue!',
#'new rule' => 'New Rule',
# 'notes' => 'Notes',
# 'ntp after boot' => 'Synchronize Time after Boot',
#'service grouping settings txt' => 'Service Grouping',
#'services settings txt' => 'Services settings',
#'shaping add options' => 'Add service',
# 'vpn ca configuration' => 'Certificate Authorities configuration',


### Net-Traffic texts (Currently unused in GUI)
#'traffic page' => 'Utilisation',
#'trafficgreen' => 'Internal net',
# 'trafficred' => 'Internet',
#'trafficorange' => 'DMZ',
#'trafficblue' => 'WLAN',
#'net-traffic disabled' => 'Net-Traffic disabled',
#'net-traffic enabled' => 'Net-Traffic enabled',
#'disable net-traffic' => 'Disable Net-Traffic',
#'enable net-traffic' => 'Enable Net-Traffic',
#'shutdown red at traffic 1' => 'Shutdown Red when',
#'shutdown red at traffic 2' => ' of the monthly volume is reached',
#'limit per dial' => 'Limit per dial',
#'limit per month' => 'Limit per month',
#'dial volume' => 'Volume per dial (MByte)',
#'email adr' => 'Email address',



### bunch from OpenVPN  (Currently unused)
#'connect' => 'OVPN Start / Connect',
#'disconnect' => 'OVPN Stop / Disconnect',
#'add new ovpn' => 'OpenVPN Settings:',
#'Remote IP' => 'Remote IP / Hostname (DynDNS):',
#'comment' => 'Description:',
#'alt ovpn' => 'OpenVPN',
#'ovpn' => 'OpenVPN',
#'ovpn log' => 'OVPN-Log',
#'ovpn config' => 'OVPN-Config',
#'ovpnstatus log' => 'OVPN-Status-Log',
#'ovpnsys log' => 'OVPN-System-Log',
#'current ovpn' => 'Active OVPN-Connection:',
#'Local VPN IP' => 'Internal Network (GREEN):',
#'Remote VPN IP' => 'VPN Subnet (e.g. 10.0.10.0/255.255.255.0):',
#'Ping'=> 'Ping :',
#'optional data'=> '3. Optional Settings:',
#'requested data' => '1. Connection Settings:',
#'Resolv'=> 'Resolv-Retry:',
#'Verbose'=> 'Verbose:',
#'choose config' => 'Choose Config',
#'generate' => 'Generate Root/Host Zertifikate',
#'test' => 'test',
#'ovpn dl' => 'OVPN-Config Download',
#'key stuff' => '2. Keys and Certificates',
#'status ovpn' => '4. OpenVPN Status / Configuration',
#'manage ovpn' => '5. Tunnel Management:',
#'genkey' => 'Generate PSK',
#'exportkey' => 'Export PSK',
#'importkey' => 'Import PSK',
#'OpenVPN' => 'OpenVPN',
#'o-yes' => 'Activ',
#'o-no' => 'Inactiv',
#'error external access' => 'Could not open /var/ipcop/xtaccess/config (external acccess could not be granted)!',
#'error config' => 'Could not open /var/ipcop/ovpn/config/ZERINA.ovpn !',
#'hint' => 'Hint:',
#'debugme' => 'Not yet implemented',
#'Act as' => 'Act as:',
#'openvpn client' => 'OpenVPN Client',
#'gen static key' => 'Generate a static Key',
#'upload static key' => 'Upload a static Key',
#'external access rule changed' => 'External access rule changed; restarting access controller',
#'openvpn server status', => 'Current OpenVPN Server Status',
#'invalid input for dhcp dns' => 'Invalid input for DHCP DNS',
#'invalid input for dhcp wins' => 'Invalid input for DHCP WINS',
#'ovpn_processprio' => 'Process priority',
#'ovpn_fastio' => 'Fast-IO',
#'ovpn_mtudisc' => 'MTU-Discovery',
#'ovpn_mssfix' => 'MSSFIX Size',
#'ovpn_fragment' => 'Fragmentsize',
#'ovpn_processprioEH' => 'Extremely high',
#'ovpn_processprioVH' => 'Very high',
#'ovpn_processprioH' => 'High',
#'ovpn_processprioEN' => 'More highly than normal',
#'ovpn_processprioN' => 'Normal',
#'ovpn_processprioLN' => 'More deeply than normal',
#'ovpn_processprioD' => 'Deeply',
#'ovpn_processprioVD' => 'Very deeply',
#'ovpn_processprioED' => 'Extremely deeply',
#'server reserved' => 'The connection name server is reserved and not allowed',
#'add-route' => 'Additional push route',
#'subnet' => 'Subnet',
#'route subnet is invalid' => 'Additional push route subnet is invalid',
#'radius settings' => 'Radius settings',
#'radius nas settings' => 'Radius NAS settings',
#'radius nas-identifier' => 'NAS-Identifier',
#'radius service-type' => 'Service-Type',
#'radius framed-protocol' => 'Framed-Protocol',
#'radius nas-port-type' => 'NAS-Port-Type',
#'radius nas-ip-address' => 'NAS-IP-Address',
#'save-radius-settings' => 'Save Radius settings',
#'broken pipe' => 'Broken pipe',
#'cant start openssl' => 'Can\'t start OpenSSL',

# from advproxy for proxy.cgi (Currently unused)
#'no cre groups' => 'There are no access groups available',
#'cre disabled' => 'The management interface has been disabled by the Administrator',
#'save and restart' => 'Save and restart',
#'LDAP auth' => 'LDAP authentication',
#'NTLM auth' => 'Windows NT/2003 authentication',
#'chgwebpwd change web password' => 'C h a n g e &nbsp; w e b &nbsp; a c c e s s &nbsp; p a s s w o r d',
#'chgwebpwd username' => 'Username',
#'chgwebpwd old password' => 'Current password',
#'chgwebpwd new password' => 'New password',
#'chgwebpwd new password confirm' => 'New password (confirm)',
#'chgwebpwd change password' => 'Change password',
#'errmsg no password' => 'Password can not be empty',
#'errmsg invalid user' => 'Username does not exist',
#'errmsg password incorrect' => 'Password incorrect',
#'errmsg change fail' => 'Password could not be changed',
#'errmsg change success'  => 'Password for web access sucessfully changed',
#'chgwebpwd SUCCESS' => 'S U C C E S S :',
#'chgwebpwd ERROR' => 'E R R O R :',

######## Stop Edit above ##########

);

# always return true
1;
